from pydantic import BaseModel

# Base schema contains the shared fields expected when creating or reading a game
class GameBase(BaseModel):
    title: str
    genre: str
    release_year: int
    rating: float
    is_completed: bool

# Schema specifically for creating a new game (inherits everything from GameBase)
class GameCreate(GameBase):
    pass
  
# Schema for reading a game from the database (includes the ID generated by the DB)
class Game(GameBase):
    id: int
    
    class Config:
        from_attributes = True
        
